### ISSUE TITLE
incorrect force field in the data/cgenff/logP_cgenff.csv file ?

### ISSUE THREAD

**Issue by iorga** [Becksteinlab/SAMPL7_logP_data#1]
In the `data/cgenff/logP_cgenff.csv` file, the force field column is `opls-aa`, which is obviously not correct. The content of the file seems to be different from those of `data/oplsaa/logP_cgenff.csv`.

@VOD555 This need to be checked, and at least change `opls-aa` into `cgenff` in the force field column.

@orbeckst Can you please update, if needed, the zenodo repo once this issue has been solved?

**Comment by iorga** [comment]
@VOD555 This need to be fixed with high priority, as we need to submit the revision for the SAMPL7-Phys-Prop paper in a few days... Thanks.

**Comment by VOD555** [comment]
@iorga I check the script which generated the results, the results are from `cgenff` and `forcefield` was set to `opls-aa` by mistake.

**Comment by orbeckst** [comment]
Did d0ef169 fix this issue, @iorga ?

**Comment by iorga** [comment]
Yes, that's good for me. Thanks @VOD555 !
