### ISSUE TITLE
original mol2 and pdb files are not included

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/SAMPL7_logP_data#3]
The original mol2 and pdb files are only present as symlinks but not as actual files. See, for example, [SM39.mol2](https://github.com/Becksteinlab/SAMPL7_logP_data/blob/main/top/cgenff/SM39/SM39.mol2) and [SM39.pdb](https://github.com/Becksteinlab/SAMPL7_logP_data/blob/main/top/cgenff/SM39/SM39.pdb) in https://github.com/Becksteinlab/SAMPL7_logP_data/tree/main/top/cgenff/SM39

This makes the data less useful, especially for checking.

All symlinks should be replaced with the actual files.

**Comment by orbeckst** [comment]
@VOD555 could you please update the repository by adding _all_ missing mol2 and pdb files? Thanks.

**Comment by iorga** [comment]
I've replaced the broken .pdb and .mol2 symlinks with the actual files in folders cgenff, gaff and oplsaa (there were no symlinks in ligpargen) and added missing folders in oplsaa (see commit d185e9ce2cf125f5ec0b79207f3613f0540feca4). Closing the issue.

**Comment by orbeckst** [comment]
Thank you very much, @iorga !!

I'll make a new release.
